name: purchase-predictor-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.3.1
  - pip:
    # Core ML and Azure dependencies
    - azure-ai-ml>=1.0.0
    - mlflow>=2.0.0
    - scikit-learn>=1.0.0
    - pandas>=1.3.0
    - numpy>=1.21.0
    - joblib>=1.1.0
    - PyYAML>=5.4.0
    - azure-identity>=1.7.0
    - python-dotenv>=1.0.0
    - piny>=1.1.0
    # Azure ML managed endpoint dependencies (CRITICAL for deployment)
    - azureml-inference-server-http>=1.0.0
    - azureml-defaults>=1.0.0
    # Azure SDK dependencies
    - typing-extensions>=4.0.0
    - msrest>=0.6.0
    # Local inference server dependencies
    - flask>=2.3.0
    - flask-cors>=4.0.0
    - gunicorn>=21.0.0
    - requests>=2.31.0