# Azure ML Configuration
# These values will be loaded from environment variables (.env.local file)

azure:
  subscription_id: "${AZURE_SUBSCRIPTION_ID}"
  resource_group: "${AZURE_RESOURCE_GROUP}"
  workspace_name: "${AZURE_WORKSPACE_NAME}"

# Model Configuration
model:
  type: "random_forest"  # Options: "random_forest", "logistic_regression"
  random_state: 42

# MLFlow Configuration
mlflow:
  experiment_name: "purchase_predictor"
  run_name: "training_run"
  artifact_path: "model"
  registered_model_name: "purchase_predictor_model"

# Model Registration
model_registration:
  name: "purchase-predictor-model"
  description: "Binary classifier for purchase prediction using customer and product features"

# Deployment Configuration
deployment:
  endpoint_name: "purchase-predictor-endpoint"
  deployment_name: "purchase-predictor-deployment"
  environment_name: "purchase-predictor-env"
  instance_type: "Standard_DS2_v2"
  instance_count: 1

# Data Configuration
data:
  train_path: "sample_data/train.csv"
  test_path: "sample_data/test.csv"
  processed_data_dir: "processed_data"
  feature_columns:
    - "price"
    - "user_rating"
    - "category_encoded"
    - "previously_purchased_encoded"
  target_column: "label"

# Model Artifacts Configuration
artifacts:
  models_dir: "models"
  run_id_file: "models/run_id.txt"
  registration_info_file: "models/registration_info.yaml"
  endpoint_info_file: "models/endpoint_info.yaml"
  local_model_file: "models/model.pkl"